#!/bin/sh

LISTNAME=$(basename $0)

create_host_line() {
  echo "$1 $2 # $LISTNAME"
}

print_usage() {
  echo "Usage: [sudo] $LISTNAME [no|yes|add|remove|list|dns_reload]"
}

block_list() {
  sed -e "s/^#\(.*# $LISTNAME\)/\1/g" /etc/hosts > /etc/hosts.new
  mv /etc/hosts.new /etc/hosts
}

unblock_list() {
  sed -e "s/\(^[^\#]*# $LISTNAME\)/#\1/g" /etc/hosts > /etc/hosts.new
  mv /etc/hosts.new /etc/hosts
}

add_host() {
  local HOST=$1

  if [ "$#" = "1" ];then
    local IP=127.0.0.1
  else
    local IP=$2
  fi
  
  echo $(create_host_line $IP $HOST) >> /etc/hosts
}

remove_host() {
  local HOST=$1
  
  sed "s/.*$HOST # $LISTNAME//g" /etc/hosts > /etc/hosts.new
  mv /etc/hosts.new /etc/hosts
}

list() {
  cat /etc/hosts | grep "# $LISTNAME" | cut -d" " -f2
}

dns_reload() {
  killall mDNSResponder
}

# Raise to sudo privileges for options requiring that
if [[ $1 != 'list' ]] && [[ ! -z $1 ]]
then
  if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    sudo $0 $*
    exit
  fi
fi

COMMAND=$1
shift

case $COMMAND in
'no')
  block_list
  ;;
'yes')
  unblock_list
  ;;
'add')
  add_host $*
  ;;
'remove')
  remove_host $*
  ;;
'list')
  list
  ;;
'dns_reload')
  dns_reload
  ;;
*)
  print_usage
  exit 1
  ;;
esac
